FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt flower

COPY . .

EXPOSE 5555

CMD ["celery", "-A", "tasks", "flower", "--port=5555"]